services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/ha:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    network_mode: host


  audiobookshelf:
    container_name:  audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    volumes:
      - /media2/audiobookshelf/config:/config
      - /media2/audiobookshelf/metadata:/metadata
      - /media2/audiobookshelf/audiobooks:/audiobooks
      - /media2/audiobookshelf/podcasts:/podcasts  
    ports:
      - "13378:80"
    restart: unless-stopped
    privileged: true
    network_mode: host



