version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    user: 1002:1002
    ports:
      - '8080:8080'
    volumes:
      - /opt/stirlingpdf/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - /opt/stirlingpdf/extraConfigs:/configs
      - /opt/stirlingpdf/customFiles:/customFiles/
      - /opt/stirlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
