#!/bin/bash
#
# 
# Set up to create user and directories if they don't exist is a to-do

podman run -d \
        -p 8080:8080 \
        -v /opt/stirlingpdf/trainingData:/usr/share/tessdata:Z \
        -v /opt/stirlingpdf/extraConfigs:/configs:Z \
        -v /opt/stirlingpdf/logs:/logs:Z \
        -e DOCKER_ENABLE_SECURITY=false \
        -e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
        -e LANGS=en_GB \
	--restart=always\
        --name stirling-pdf \
        frooodle/s-pdf:latest

#        -e PUID=1002 \
#        -e PGID=1002 \
